```{r setup, echo=FALSE, warning=FALSE, purl=FALSE, message=FALSE}
options(repos="http://cran.rstudio.com/")
pkgs <- c("sp","rgdal","rgeos","raster")
lapply(pkgs, library, character.only = TRUE)
```

# Reading and Writing Raster and Vector Data
So, now that we have the base packages installed and loaded we can work on 

## Lesson Outline
- [Vector data: shapefiles](#vector-data-shapefiles)
- [Vector data: file geodatabase](#vector-data-file-geodatabase])
- [Vector data: geojson](#vector-data-geojson)
- [Raster data: esri grids](#raster-data-esri-grids)
- [Raster data: ASCII](#raster-data-ascii)
- [Raster data: common image formats](#raster-data-common-image-formats)
- [Geospatial data packages](#geospatial data packages)

## Lesson Exercises
- [Exercise 2.1](#exercise-21)
- [Exercise 2.2](#exercise-22)

## Vector data: shapefiles

## Vector data: file geodatabase

## Vector data: geojson

## Exercise 2.1

## Raster data: esri grids

## Raster data: ASCII

## Raster data: common image formats

## Exercise 2.2

## Geospatial data packages
- maps
- USCensus

