```{r setup, echo=FALSE, warning=FALSE, purl=FALSE, message=FALSE}
options(repos="http://cran.rstudio.com/")
pkgs <- c("sf","sp","rgdal","rgeos","raster","knitr")
x<-lapply(pkgs, library, character.only = TRUE)
opts_chunk$set(tidy=T)
```

# Spatial/GIS Analysis with R

Given the size of this topic and limited time we have to spend on it this introduction of Spatial and GIS analyses with R is going to focus on one type of spatial data, vector, and one class of spatail data structures in r, simple features.

## Lesson Outline
- [Required packages](#required-spatial-packages)
- [Read in spatial data](#read-in-spatial-data)
- [Spatial data manipulation](#spatial-data-manipulation)
- [Projections](#projections)
- [Spatial data visualization](#spatial-data-visualization)
- [Example spatial workflow](#example-spatial-workflow)

## Lesson Exercises
- [Exercise 1](#exercise-1)
- [Exercise 2](#exercise-2)
- [Exercise 3](#exercise-3)

## Required packages

## Read in spatial data

## Exercise 1

## Spatial data manipulation

## Projections

## Exercise 2

## Spatial data visualization

## Exercise 3

## Example spatial workflow


